### ISSUE TITLE
01.02.02 on DNN 7.3.4 Registered Users MUST be selected in Allowed Roles or module generates an Exception

### ISSUE THREAD

**Issue by djamell** [DNN-Connect/UserAccountManagement#17]
Hi Philipp,

Thank you for this module.  I'm very excited to finally have this functionality in DNN.

I'm Running DNN 7.3.4 and I'm having a problem similar to others, but I'm able to correct it by selecting "Registered Users" in the "Allowed Roles".

Steps to reproduce problem.

1. Place new instance of the module on a page

2. Open the Module Settings Page (NOTE: You do not even have to select the "Account Module Settings" Tab)

2. Click Update

I get the following:

------ Begin Error ------

[NullReferenceException: Object reference not set to an instance of an object.]
   Connect.Modules.UserManagement.AccountManagement.View.PersonalizeOptions() +2493
   Connect.Modules.UserManagement.AccountManagement.View.Page_Load(Object sender, EventArgs e) +116
   System.Web.UI.Control.LoadRecursive() +70
   System.Web.UI.Control.LoadRecursive() +189
   System.Web.UI.Control.LoadRecursive() +189
   System.Web.UI.Control.LoadRecursive() +189
   System.Web.UI.Control.LoadRecursive() +189
   System.Web.UI.Control.LoadRecursive() +189
   System.Web.UI.Control.LoadRecursive() +189
   System.Web.UI.Control.LoadRecursive() +189
   System.Web.UI.Control.LoadRecursive() +189
   System.Web.UI.Control.LoadRecursive() +189
   System.Web.UI.Control.LoadRecursive() +189
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3177

[PageLoadException: Object reference not set to an instance of an object.]
   DotNetNuke.Services.Exceptions.Exceptions.ProcessPageLoadException(Exception exc, String URL) +606
   DotNetNuke.Framework.PageBase.OnError(EventArgs e) +556
   System.Web.UI.Page.HandleError(Exception e) +164
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +12308351
   System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +12307881
   System.Web.UI.Page.ProcessRequest() +119
   System.Web.UI.Page.ProcessRequest(HttpContext context) +99
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +913
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +165

------ End Error ------

If I go "Back" in the browser to return to the Module Settings Page, select "Registered Users" in the "Allowed Roles" and Update it works!

After some experimentation with the "Allowed Roles" and "Preselected Role" I could not find any combination that didn't generate the error except when the Registered Users is selected.

**Comment by peppertree** [comment]
This should be fixed for 1.3.0
