### ISSUE TITLE
Export selection

### ISSUE THREAD

**Issue by vmasanas** [DNN-Connect/UserAccountManagement#21]
I was expecting that the "Export selection" button just export the users that are actually selected (checkbox active) on the grid. I notice (and verified on the code) that this is not true, what it does is export all rows in the grid.

Is that the expected behavior?
- if yes: maybe we should rename the button to something like "export current view" or similar
- if not: fix the code export just selected rows

**Comment by peppertree** [comment]
It's expected. That feature was there before we got the chechboxes.

**Comment by vmasanas** [comment]
Ok, then I suggest we change the "Export selection" to "Export Current" or similar

**Comment by peppertree** [comment]
Fixed
